// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYZ6NWjaOkoS4SoaG0tjkZKSOb16WfXg',
    appId: '1:491488908806:web:4b37959e8175e7b5401587',
    messagingSenderId: '491488908806',
    projectId: 'melkk-dev',
    authDomain: 'melkk-dev.firebaseapp.com',
    storageBucket: 'melkk-dev.firebasestorage.app',
    measurementId: 'G-190ZFFSDK9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHogGxZpv-W_EiI-3sMA7lVMg0ASYm6xw',
    appId: '1:491488908806:ios:e5d673967b668d15401587',
    messagingSenderId: '491488908806',
    projectId: 'melkk-dev',
    storageBucket: 'melkk-dev.firebasestorage.app',
    iosBundleId: 'com.mellkdev.portfolio',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPY3jrZZa3BvbPNmOY7hagfXaEQ9VjzvQ',
    appId: '1:491488908806:android:0c6357f7301e99a5401587',
    messagingSenderId: '491488908806',
    projectId: 'melkk-dev',
    storageBucket: 'melkk-dev.firebasestorage.app',
  );
}
